env:
  global:
    - CC_TEST_REPORTER_ID=d83745e6c5240eca8212feff6d665d5b21d81185bd53f349ccb931762dc7d78b
language: node_js
install:
  - npm install
node_js:
  - "8"
before_script:
  - "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter"
  - "chmod +x ./cc-test-reporter"
  - "./cc-test-reporter before-build"
  - "cp .env.example .env"
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
